### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *Need a refactoring to follow last packaging standards*
- *Outdated*
- *The stable version doesn't store the value of is_public. In case of upgrade, the upgrade script can't know is the app is public or not.*

## Solution
- *Package refactored to adjust to latest standards*
- *Updated to version 1.1.1*
- *If is_public is empty, try to find unprotected_uris in the config file to know ifg the app is public or not.
Then set and store the value.*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.

## Validation
---
*Minor decision*
- [x] **Upgrade previous version** : JimboJoe
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [ ] **Approval (LGTM)** : 
- [x] **CI succeeded** : [Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/zerobin_ynh%20testing%20(Official)/)  
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by anmol26s** [comment]
Please update to version 1.1.1 which brings fixes to data leak vulnerabilities.see here https://github.com/PrivateBin/PrivateBin/releases

**Comment by JimboJoe** [comment]
@anmol26s Could you please possibly make a PR on testing to code that enhancement?

**Comment by maniackcrudelis** [comment]
Some very old version (?) (without fetch list before installation with a VM) doesn't have any backup script.
This should be fixed, maybe directly in the helper.

**Comment by maniackcrudelis** [comment]
A PR is waiting for that https://github.com/YunoHost/yunohost/pull/388

**Comment by maniackcrudelis** [comment]
https://github.com/YunoHost/yunohost/pull/388 is merged in stable. Let's go forward.

**Comment by maniackcrudelis** [comment]
Ready to be reviewed.
@YunoHost-Apps/apps-group

**Comment by JimboJoe** [comment]
So, is this plan still THE plan...? 😉

**Comment by maniackcrudelis** [comment]
Of course. Soon the world will be ours !

**Comment by maniackcrudelis** [comment]
Let's merge in 3 days.

**Pull request merged**
